micronaut:
  application:
    name: keyManager

grpc:
  server:
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/micronaut`}
    username: ${JDBC_USER:dbuser}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true